os:
  - linux
  - osx
language: bash
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; ci/mac ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; ci/linux ; fi
  - ./config-expect.sh
  - po install
script:
  - po init test && cd test
  - po photon build
  - po electron clean
  - po electron build
  - po P1 clean
  - po P1 build
  - po core clean
  - po core build
