os:
  - linux
  - osx
language: bash
sudo: required
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash -x ci/mac ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash -x ci/linux ; fi
  - po
  - ./config-expect.sh
  - po install
script:
  - po init test && cd test
  - po photon build
  - po electron build
  - po P1 build
  - po core build
