#     ______    ______
#    /      \  /      \
#   /██████  |/██████  |  The Future of po-util:
#   ██ |  ██ |██ |  ██ |
#   ██ |__██ |██ \__██ |      Refactored,
#   ██    ██/ ██    ██/       Modular,
#   ███████/   ██████/        Cross-Compatible
#   ██ |
#   ██ |
#   ██/  https://po-util.com

os:
  - linux
  - osx
language: bash
sudo: required
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash -x ci/mac ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash -x ci/linux ; fi
  - po
  - po config v1.0.0
  - po info
  - po install
script:
  - po init test
  - particle project create . --name test-beta
  - po photon build test
  - po photon build-beta test-beta
  - po electron build test
  - po electron build-beta test-beta
  - po P1 build test
  - po P1 build-beta test-beta
  - po core build test
  - po core build-beta test-beta
  - po config v0.8.0-rc.27
  - po setup-mesh
  - po xenon build test
  - po xenon build-beta test-beta
  - po argon build test
  - po argon build-beta test-beta
  - po boron build test
  - po boron build-beta test-beta
